#!/bin/sh

cat $1 | grep '^\[#[0-9]\+\] .\+'

if [ "$?" != "0" ]; then
    echo "ERROR: There's no story assigned to your current work!"
    echo 
    echo "Save a story ID in the '.pivotal' dotfile in project root directory"
    echo "or specify it in \$STORY environment variable."
    echo
    echo "If it's fine, that no story should be assigned to this particular"
    echo "commit, re-run commit command with '--no-verify' switch. But you"
    echo "must be aware that this approach will skip all other validations."
    echo
    echo "Aborting..."

    exit 1
fi
