#!/bin/sh

cat $1 | grep '^\[#[0-9]\+\] .\+'

if [ "$?" != "0" ]; then
    echo "ERROR! There's no story assigned to your current work! Save a story"
    echo "story ID in the '.pivotal' dotfile in project root directory or specify"
    echo "it in \$STORY environment variable."
    echo

    exec < /dev/tty
    read -p "Do you want to commit anyway? (y/N) " answer

    if [ "$answer" != "y" ] && [ "$answer" != "Y" ]; then
        echo
        echo "Aborting..."
        exit 1
    else
        echo
    fi
fi
