#!/bin/sh

if [ "$(git symbolic-ref HEAD 2>/dev/null)" == "refs/heads/master" ]; then
    echo "ERROR! You shouldn't commit directly to 'master'. If you're working"
    echo "on some issues or new features then you should get it done in a separate"
    echo "branch and merge changes to master after you finish."
    echo
    
    exec < /dev/tty
    read -p "Do you want to commit anyway? (y/N) " answer

    if [ "$answer" != "y" ] && [ "$answer" != "Y" ]; then
        echo
        echo "Aborting..."
        exit 1
    else
        echo
    fi
fi
